extends "res://tests/network_test.gd"
## Run with an isolated APPDATA directory. Run again with -- --restart to verify disk defaults.


func run() -> void:
	var client := make_sector("Client")
	client.client_only = true
	var session := client.session
	session.open_menu()
	await settle()
	if "--restart" in OS.get_cmdline_user_args():
		check(session.address.text == "localhost" and int(session.port_field.value) == 24731, "Successful endpoint survives a new client process and subsequent failed attempts")
		check(not session.active and not session.connecting and not session.join_button.disabled, "Restart opens a usable menu without auto-connecting")
		finish()
		return
	var defaults := ConnectionPreferences.new()
	defaults.load_from("user://missing.cfg")
	check(defaults.address == "127.0.0.1" and defaults.port == FlightSession.PORT, "Missing preferences retain defaults")
	var invalid := ConfigFile.new()
	invalid.set_value("connection", "address", 123)
	invalid.set_value("connection", "port", 99999)
	invalid.save("user://invalid.cfg")
	defaults.load_from("user://invalid.cfg")
	check(defaults.address == "127.0.0.1" and defaults.port == FlightSession.PORT, "Invalid preference types and ranges retain defaults")
	defaults.remember("localhost", 24731, "user://missing-directory/connection.cfg")
	check(defaults.save_failed, "Unwritable preferences report failure without blocking play")
	check(session.join("   ") == ERR_INVALID_PARAMETER, "Blank address is rejected locally")
	await settle()
	check(session.menu.visible and not session.join_button.disabled and session.address.editable, "Blank address leaves editable menu")
	var server := make_sector("Server")
	check(server.session.host(24731) == OK, "Test server opens its own UDP port")
	session.address.text = " localhost "
	session.port_field.get_line_edit().text = "24731"
	session.join_button.pressed.emit()
	await settle(0.5)
	check(session.active and not session.menu.visible, "Menu submits edited port and connects to a real server")
	check(session.address.text == "localhost" and session.preferences.port == 24731, "Successful endpoint is normalized and remembered")
	session.open_menu()
	await settle()
	session.leave_button.pressed.emit()
	await settle()
	check(session.menu.visible and session.address.text == "localhost" and int(session.port_field.value) == 24731, "Manual disconnect preserves both fields")
	check(session.join_button.has_focus() and not session.join_button.disabled, "Disconnect focuses manual reconnect")
	session.join_button.pressed.emit()
	await settle(0.5)
	check(session.active, "One button reconnects to the same server")
	server.session.disconnect_session("Test shutdown")
	await settle(0.5)
	check(session.menu.visible and not session.active and session.address.editable, "Server loss returns to editable menu")
	session.join("127.0.0.1", 24689)
	await settle()
	check(session.leave_button.text == "Cancel connection" and session.leave_button.has_focus(), "Connecting offers a focused cancel button")
	check(session.status_label.text.contains("UDP 24689") and session.status_label.text.contains("10 seconds"), "Connecting identifies endpoint and actual timeout")
	session.leave_button.pressed.emit()
	await settle()
	check(not session.connecting and session.address.editable, "Cancel immediately restores editable fields")
	session.join_button.pressed.emit()
	session.tick(FlightSession.CONNECT_TIMEOUT)
	await settle()
	check(session.menu.visible and not session.connecting and not session.join_button.disabled, "Timeout leaves manual retry usable")
	check(session.status_label.text.contains("UDP 24689") and session.status_label.text.contains("No connection"), "Timeout reports attempted endpoint without guessing a network cause")
	var saved := ConnectionPreferences.new()
	saved.load_from()
	check(saved.address == "localhost" and saved.port == 24731, "Failed and cancelled attempts do not replace successful preferences")
	finish()
