extends "res://tests/shop_test.gd"
## Docked admission, server authority, real preparation transactions and launch.


func run() -> void:
	var server := make_sector("MenuServer", true, 24739)
	check(server.session.store.commit({"pilot0": 19000}), "Seed a preparation budget")
	var observer := make_sector("FlyingPilot")
	observer.session.credential_id = "pilot1"
	observer.session.credential_token = test_token(1)
	observer.session.join("127.0.0.1", test_port(24739))
	await settle(0.5)
	var client := make_sector("DockedPilot")
	client.client_only = true
	client.get_viewport().size = Vector2i(960, 600)
	client.session.credential_id = "pilot0"
	client.session.credential_token = test_token(0)
	client.session.join("127.0.0.1", test_port(24739))
	await settle(0.5)
	await replicate(server)
	var id := client.multiplayer.get_unique_id()
	var menu := client.main_menu
	check(client.preflight and client.paused and menu.visible and menu.home.visible, "Normal connection opens the docked main menu")
	check(client.credits == 19000 and not menu.start_button.disabled, "Main menu receives saved credits and enables launch after sync")
	check(menu.wallet.text == "19,000 CR" and menu.ship_title.text == "LIBERATOR" and menu.stat_values["damage"].text == "65", "Overview presents the synchronized wallet, active hull and fitting")
	check(not menu.notice.visible, "Overview omits flight instructions and permanent filler")
	check(menu.ship_art.model_id == "liberator" and menu.ship_art.stage.own_world_3d and menu.ship_art.stage.transparent_bg, "Docked overview renders the active hull separately over the approved menu backdrop")
	await press(client, KEY_M)
	check(not client.hud.navigation.overview.visible and menu.home.visible, "Docked menu does not open the flight map")
	check(not observer.session.ships.has(id), "Docked pilot is absent from another pilot's map")
	var ship := server.session.ships[id]
	check(ship.get_meta("docked") and not ship.visible and ship.collision_layer == 0, "Server docked ship is invisible and has no collision")
	var origin := ship.position
	client.session.command_flight.rpc_id(1, Vector3(0, 0, -1), Vector3.ZERO, true, true)
	await settle()
	server.session.tick(0.1)
	check(ship.position == origin and not server.session.commands.has(id), "Forged movement and fire are rejected while docked")
	ship.position = server.alien.position
	check(server.session.combat.choose_target(server.alien) != ship, "Aliens cannot target docked pilots even outside station protection")
	server.loot.spawn_drop(server.alien)
	server.loot.drops[server.loot.drops.keys()[0]]["position"] = ship.position
	server.session.combat.collect_loot()
	check(CargoResources.units(server.session.combat.cargo_holds[id]["starter"]) == 0, "Docked pilot cannot collect space loot")
	ship.position = origin
	if DisplayServer.get_name() != "headless":
		client.get_viewport().render_target_update_mode = SubViewport.UPDATE_ALWAYS
		var screen := TextureRect.new()
		screen.texture = client.get_viewport().get_texture()
		root.add_child(screen)
		root.size = Vector2i(960, 600)
	for dimensions in [Vector2i(960, 600), Vector2i(1440, 900)]:
		client.get_viewport().size = dimensions
		await settle()
		var bounds := Rect2(Vector2.ZERO, Vector2(dimensions))
		check(bounds.encloses(menu.home.get_global_rect()) and bounds.encloses(menu.start_button.get_global_rect()), "Overview and Start fit at %s" % dimensions)
		await capture(client, "main-menu-%d" % dimensions.x)
		check(server.session.store.commit({"pilot0": PilotStore.MAX_CREDITS}), "Set the supported wallet limit for layout validation")
		await replicate(server)
		check(bounds.encloses(menu.wallet.get_global_rect()) and bounds.encloses(menu.wallet_icon.get_global_rect()) and not menu.wallet.get_global_rect().intersects(menu.wallet_icon.get_global_rect()), "Large synchronized credit balances and the wallet icon fit the header without overlap")
		check(server.session.store.commit({"pilot0": 19000}), "Restore the preparation budget")
		await replicate(server)
		for button: Button in menu.navigation.values():
			check(bounds.encloses(button.get_global_rect()), "Left navigation fits at %s" % dimensions)
		for page: String in ["shop", "hangar", "quests", "cargo", "skylab", "gates"]:
			await click(client, menu.navigation[page])
			var panel: Control = {"shop": client.shop, "hangar": client.equipment_menu, "quests": client.hud.contract_panel, "cargo": client.shop, "skylab": client.skylab_menu, "gates": menu.placeholder}[page]
			check(panel.visible and bounds.encloses(panel.get_global_rect()), "Page %s fits beneath navigation at %s" % [page, dimensions])
			check(menu.content_rect().encloses(panel.get_global_rect()), "Page %s leaves the header and left navigation accessible" % page)
			check(not menu.start_button.is_visible_in_tree() and not menu.specifications.is_visible_in_tree(), "Overview footer is hidden on %s" % page)
			check(client.equipment_menu.specifications.is_visible_in_tree() == (page == "hangar"), "Only Hangar retains its own specifications strip on %s" % page)
			if page == "hangar":
				check(client.equipment_menu.stat_values["damage"].text == menu.stat_values["damage"].text and client.equipment_menu.stat_values["cargo"].text == menu.stat_values["cargo"].text, "Hangar specifications use the synchronized fitting and cargo")
				check(client.equipment_menu.get_global_rect().encloses(client.equipment_menu.specifications.get_global_rect()), "Hangar's full-width specifications remain inside the page")
				check(client.equipment_menu.specifications.size.y < 160, "Hangar specifications retain a compact horizontal layout")
			await capture(client, "main-menu-%s-%d" % [page, dimensions.x])
			await press(client, KEY_ESCAPE)
			check(client.preflight and client.paused and menu.home.visible, "Esc returns from %s without launching" % page)
		await click(client, menu.navigation["settings"])
		for tab in range(client.settings_menu.tabs.get_tab_count()):
			client.settings_menu.tabs.current_tab = tab
			await settle()
			check(menu.content_rect().encloses(client.settings_menu.panel.get_global_rect()), "Settings tab %d leaves navigation accessible at %s" % [tab, dimensions])
			check(not menu.start_button.is_visible_in_tree() and not client.equipment_menu.specifications.is_visible_in_tree(), "Settings tab %d has neither Start nor ship specifications" % tab)
			await capture(client, "main-menu-settings-%d-%d" % [tab, dimensions.x])
		client.settings_menu.tabs.current_tab = 0
		await press(client, KEY_ESCAPE)
		await click(client, menu.navigation["connection"])
		check(menu.content_rect().encloses(client.session.menu.get_global_rect()) and not menu.start_button.is_visible_in_tree(), "Connection fits within docked navigation without Start at %s" % dimensions)
		check(not client.session.address.editable and not client.session.port_field.editable and client.session.join_button.disabled and not client.session.leave_button.disabled, "Connected fields and actions reflect session state")
		await capture(client, "main-menu-connection-%d" % dimensions.x)
		await press(client, KEY_ESCAPE)
	for shortcut: Key in [KEY_B, KEY_I, KEY_C]:
		await press(client, shortcut)
		check(not menu.home.visible and not menu.start_button.is_visible_in_tree(), "Keyboard station navigation hides Overview and Start")
		await press(client, KEY_ESCAPE)
		check(menu.home.visible and menu.start_button.is_visible_in_tree(), "Keyboard Back restores the Overview footer")
	await click(client, menu.navigation["settings"])
	check(client.settings_menu.panel.visible and not client.settings_menu.pause_panel.visible, "Settings opens without a flight pause panel")
	check(not menu.start_button.is_visible_in_tree(), "Settings does not expose Start")
	client.settings_menu.close()
	await settle()
	check(menu.home.visible and client.paused, "Settings returns to the docked overview")
	await click(client, menu.navigation["connection"])
	check(client.session.menu.visible, "Connection management remains accessible")
	check(not menu.start_button.is_visible_in_tree(), "Connection does not expose Start")
	client.session.back_button.pressed.emit()
	await settle()
	check(menu.home.visible and not client.session.menu.visible and client.paused, "Connection Back returns to overview")
	await click(client, menu.navigation["shop"])
	await click(client, client.shop.buys["laser"])
	await replicate(server)
	check(client.credits == 9000 and client.session.combat.inventory["items"].has("purchase-1"), "Docked shop purchase commits to persistent inventory")
	await click(client, menu.navigation["hangar"])
	await capture(client, "main-menu-hangar-owned")
	check(client.equipment_menu.ship_art.texture == StationUi.texture("liberator"), "Hangar uses the current Godot-rendered Liberator asset")
	client.equipment_menu.move_item("purchase-1", "laser2")
	await settle()
	await replicate(server)
	check(ship.laser_damage == 130 and client.session.combat.inventory["items"]["purchase-1"]["slot"] == "laser2", "Docked hangar installs the purchased laser authoritatively")
	client.equipment_menu.select_item("purchase-1")
	client.equipment_menu.preview_removal()
	await settle()
	check(client.equipment_menu.remove_button.visible and client.equipment_menu.preview.text.contains("65 damage") and client.equipment_menu.stat_values["damage"].text == "130", "Installed-item selection exposes Remove and a proposed fitting without changing current stats")
	await capture(client, "main-menu-hangar-selected")
	await click(client, menu.navigation["shop"])
	client.shop.select_category("ships")
	client.shop.select_model("phoenix")
	await settle()
	await click(client, client.shop.buys["phoenix"])
	await replicate(server)
	var phoenix := ShipCatalog.owned_id(client.session.combat.inventory, "phoenix")
	check(not phoenix.is_empty(), "Docked shop can buy a hull into the hangar")
	await click(client, menu.navigation["hangar"])
	client.equipment_menu.ship_choice.select(client.equipment_menu.owned_ships.find(phoenix))
	await settle()
	await click(client, client.equipment_menu.activate_button)
	await replicate(server)
	check(ship.ship_model == "phoenix" and client.player.ship_model == "phoenix" and not ship.visible and ship.collision_layer == 0, "Docked ship activation updates the hull without entering the map")
	check(menu.ship_art.model_id == "phoenix", "Hangar preview follows the server-confirmed hull switch")
	check(client.equipment_menu.ship_art.texture == StationUi.texture("phoenix"), "Hangar switches to the current Phoenix render without cropping its relative scale")
	await click(client, menu.navigation["overview"])
	check(menu.home.visible and menu.start_button.is_visible_in_tree() and menu.ship_title.text == "PHOENIX" and menu.last_model == "phoenix" and menu.stat_values["damage"].text == "0" and menu.wallet.text == "9,000 CR", "Overview navigation returns to the updated active ship, fitting and wallet")
	await click(client, menu.navigation["hangar"])
	client.equipment_menu.ship_choice.select(client.equipment_menu.owned_ships.find("starter"))
	await settle()
	await click(client, client.equipment_menu.activate_button)
	await replicate(server)
	check(ship.ship_model == "liberator" and ship.laser_damage == 130, "Switching back retains the prepared Liberator fitting")
	await click(client, menu.navigation["quests"])
	await click(client, client.hud.contract_accept)
	await replicate(server)
	check(not client.active_contracts.is_empty(), "Docked quest board accepts a saved hunt")
	await click(client, client.hud.contract_tabs[1])
	check(client.hud.contract_abandon.visible and not client.hud.contract_accept.visible and not client.hud.contract_empty.visible, "Active quest tab keeps progress and its Abandon action")
	await capture(client, "main-menu-quests-active")
	await click(client, menu.navigation["overview"])
	await click(client, menu.start_button)
	client.session.launch_request.rpc_id(1)
	await settle()
	await replicate(server)
	check(not client.preflight and not client.paused and not menu.visible and not client.hud.contract_panel.visible, "Start closes preparation screens and enters flight")
	check(menu.ship_art.stage.render_target_update_mode == SubViewport.UPDATE_DISABLED, "Launched flight does not render the hidden hangar")
	check(not ship.get_meta("docked") and ship.visible and ship.collision_layer == 2, "Launch enables the server ship and collision")
	var delayed := server.session.combat.pack_player(id)
	delayed.merge({"docked": true, "position": ship.position, "rotation": ship.rotation, "velocity": ship.velocity, "energy": ship.energy}, true)
	client.session.snapshot({id: delayed}, {}, client.session.player_sequences[id] + 1)
	check(client.player.visible and client.player.collision_layer == 2, "Delayed docked snapshot cannot hide a launched ship")
	check(observer.session.ships.has(id) and observer.session.ships[id].laser_damage == 130, "Other pilots see the equipped ship after launch")
	check(ship.laser_damage == 130 and client.credits == 9000 and not client.active_contracts.is_empty(), "Launch preserves fitting, wallet and accepted quest")
	check(server.session.ships.size() == 2, "Repeated launch creates no duplicate ship")
	await check_flight_pages(client, "connected")
	check(not ship.get_meta("docked") and ship.collision_layer == 2 and observer.session.ships.has(id), "Flight menus retain the live server ship and observer visibility")
	client.session.command_flight.rpc_id(1, Vector3(0, 0, -1), Vector3.ZERO, true, false, int(client.player.get_meta("life", 0)))
	await settle()
	server.session.tick(0.1)
	check(ship.position.z < origin.z, "Launched ship can fly")
	await press(client, KEY_M)
	check(client.hud.navigation.overview.visible, "Launched pilot retains the sector overview")
	client.session.quit_to_menu()
	await replicate(server)
	check(not client.hud.navigation.overview.visible and menu.home.visible, "Returning to the menu closes an open sector overview")
	await click(client, menu.start_button)
	await replicate(server)
	ship.position = Vector3(0, 100, -200)
	ship.hull = 50000
	ship.shield = 350
	ship.energy = 42
	ship.shot_cooldown = 0.3
	ship.time_since_hit = 3
	server.alien.contributors.assign([id, observer.multiplayer.get_unique_id()])
	await replicate(server)
	var old_life: int = ship.get_meta("life")
	var old_flight := server.session.combat.pack_player(id)
	old_flight.merge({"position": ship.position, "rotation": ship.rotation, "velocity": ship.velocity, "energy": ship.energy})
	client.client_only = false # Joining from the offline development client must retain return navigation.
	for dimensions in [Vector2i(960, 600), Vector2i(1440, 900), Vector2i(1920, 1080)]:
		client.get_viewport().size = dimensions
		client.set_paused(true)
		await settle()
		check(client.settings_menu.main_menu_button.visible and Rect2(Vector2.ZERO, Vector2(dimensions)).encloses(client.settings_menu.pause_panel.get_global_rect()), "Quit to main menu fits the flight menu at %s" % dimensions)
		var pause := client.settings_menu.pause_panel.get_global_rect()
		check(pause.size.x >= 500 and pause.size.y <= 450 and client.settings_menu.resume_button.get_global_rect().size.y >= 36, "Connected flight menu has readable proportions at %s" % dimensions)
		await capture(client, "quit-to-menu-%d" % dimensions.x)
	client.auto_fire = true
	client.select_target(client.alien)
	await click(client, client.settings_menu.main_menu_button)
	client.client_only = true
	client.session.dock_request.rpc_id(1)
	await replicate(server)
	check(client.session.active and client.multiplayer.get_unique_id() == id and client.preflight and menu.visible and client.paused, "Quit returns to the full main menu without disconnecting")
	check(not observer.session.ships.has(id) and ship.get_meta("docked") and ship.collision_layer == 0, "Quitting removes the ship from other pilots' maps")
	check(client.target == null and not client.auto_fire and not server.session.commands.has(id), "Quitting clears targeting and fire commands")
	check(ship.position == origin and ship.velocity == Vector3.ZERO and ship.get_meta("life") == old_life + 1, "Quit docks at the station once and invalidates the previous flight")
	check(ship.hull == 50000 and ship.shield == 350 and ship.energy == 42 and ship.shot_cooldown == 0.3 and ship.time_since_hit == 3, "Quit preserves health, charge, boost, cooldown and damage timer")
	check(id not in server.alien.contributors and observer.multiplayer.get_unique_id() in server.alien.contributors, "Leaving the map clears only the departing pilot's encounter contribution")
	client.session.snapshot({id: old_flight}, {}, client.session.player_sequences[id] + 1)
	check(not client.player.visible and client.player.collision_layer == 0 and client.player.position == origin, "Delayed flight snapshot cannot restore a docked ship")
	client.session.command_flight.rpc_id(1, Vector3(0, 0, -1), Vector3.ZERO, true, true, old_life)
	await settle()
	check(not server.session.commands.has(id), "Old flight commands remain rejected after quitting")
	await click(client, menu.navigation["shop"])
	check(menu.home.visible and not client.shop.visible and menu.notice.text.contains("five seconds"), "Recent damage keeps the overview visible with a station-service explanation")
	server.session.combat.tick(2.0)
	await replicate(server)
	check(ship.time_since_hit == 5 and ship.shot_cooldown == 0 and ship.shield == 350, "Station cooldown expires in the menu without an instant shield refill")
	await click(client, menu.navigation["hangar"])
	check(client.equipment_menu.visible and client.session.combat.inventory["items"]["purchase-1"]["slot"] == "laser2", "Returned pilot can access the prepared hangar")
	await click(client, menu.navigation["overview"])
	await click(client, menu.start_button)
	await replicate(server)
	check(not client.preflight and observer.session.ships.has(id) and ship.hull == 50000 and ship.shield == 350 and ship.energy == 42 and ship.laser_damage == 130 and client.credits == 9000 and not client.active_contracts.is_empty(), "Relaunch preserves ship state and progression and restores observer visibility")
	client.session.command_flight.rpc_id(1, Vector3(0, 0, -1), Vector3.ZERO, true, true, old_life)
	await settle()
	check(not server.session.commands.has(id), "A previous flight's commands cannot control the relaunched ship")
	# Rescue remains authoritative even when the pilot quits during its countdown.
	ship.take_damage(ship.max_hull + ship.max_shield + 1, server.alien)
	await replicate(server)
	await press(client, KEY_ESCAPE)
	await click(client, client.settings_menu.main_menu_button)
	await replicate(server)
	var rescue_wallet := client.credits
	check(client.preflight and not client.player.alive and menu.start_button.disabled, "A destroyed pilot can quit to the menu while rescue is pending")
	client.session.launch_request.rpc_id(1)
	await settle()
	check(ship.get_meta("docked") and not ship.alive, "Server rejects launch before rescue completes")
	server.session.combat.tick(3.1)
	await replicate(server)
	await settle()
	check(client.player.alive and not client.player.visible and ship.collision_layer == 0 and not menu.start_button.disabled and client.credits == rescue_wallet, "Rescue completes in the menu without launching or charging twice")
	client.session.disconnect_session("Reconnect test")
	await settle()
	client.session.join("127.0.0.1", test_port(24739))
	await settle(0.5)
	await replicate(server)
	check(client.preflight and menu.visible and client.credits == rescue_wallet and client.player.laser_damage == 130 and not client.active_contracts.is_empty(), "Reconnect restores progression and requires a new explicit launch")
	server.session.disconnect_session("Server shutdown test")
	await settle()
	check(not client.preflight and not menu.visible and client.session.menu.visible, "Server loss clears preparation and returns to connection menu")
	finish()
