extends "res://tests/shop_test.gd"
## Docked admission, server authority, real preparation transactions and launch.


func run() -> void:
	var server := make_sector("MenuServer", true, 24739)
	check(server.session.store.commit({"pilot0": 12000}), "Seed a preparation budget")
	var observer := make_sector("FlyingPilot")
	observer.session.credential_id = "pilot1"
	observer.session.credential_token = test_token(1)
	observer.session.join("127.0.0.1", 24739)
	await settle(0.5)
	var client := make_sector("DockedPilot")
	client.client_only = true
	client.get_viewport().size = Vector2i(960, 600)
	client.session.credential_id = "pilot0"
	client.session.credential_token = test_token(0)
	client.session.join("127.0.0.1", 24739)
	await settle(0.5)
	await replicate(server)
	var id := client.multiplayer.get_unique_id()
	var menu := client.main_menu
	check(client.preflight and client.paused and menu.visible and menu.home.visible, "Normal connection opens the docked main menu")
	check(client.credits == 12000 and not menu.start_button.disabled, "Main menu receives saved credits and enables launch after sync")
	check(not observer.session.ships.has(id), "Docked pilot is absent from another pilot's map")
	var ship := server.session.ships[id]
	check(ship.get_meta("docked") and not ship.visible and ship.collision_layer == 0, "Server docked ship is invisible and has no collision")
	var origin := ship.position
	client.session.command_flight.rpc_id(1, Vector3(0, 0, -1), Vector3.ZERO, true, true)
	await settle()
	server.session.tick(0.1)
	check(ship.position == origin and not server.session.commands.has(id), "Forged movement and fire are rejected while docked")
	ship.position = server.alien.position
	check(server.session.combat.choose_target(server.alien) != ship, "Aliens cannot target docked pilots even outside station protection")
	server.loot.spawn_drop(server.alien)
	server.loot.drops[server.loot.drops.keys()[0]]["position"] = ship.position
	server.session.combat.collect_loot()
	check(CargoResources.units(server.session.combat.cargo_holds[id]["starter"]) == 0, "Docked pilot cannot collect space loot")
	ship.position = origin
	if DisplayServer.get_name() != "headless":
		client.get_viewport().render_target_update_mode = SubViewport.UPDATE_ALWAYS
		var screen := TextureRect.new()
		screen.texture = client.get_viewport().get_texture()
		root.add_child(screen)
		root.size = Vector2i(960, 600)
	for dimensions in [Vector2i(960, 600), Vector2i(1440, 900)]:
		client.get_viewport().size = dimensions
		await settle()
		var bounds := Rect2(Vector2.ZERO, Vector2(dimensions))
		check(bounds.encloses(menu.home.get_global_rect()) and bounds.encloses(menu.start_button.get_global_rect()), "Overview and Start fit at %s" % dimensions)
		await capture(client, "main-menu-%d" % dimensions.x)
		for page: String in ["shop", "hangar", "quests", "cargo", "skylab", "gates"]:
			await click(client, menu.navigation[page])
			var panel: Control = {"shop": client.shop, "hangar": client.equipment_menu, "quests": client.hud.contract_panel, "cargo": client.shop, "skylab": menu.placeholder, "gates": menu.placeholder}[page]
			check(panel.visible and bounds.encloses(panel.get_global_rect()), "Page %s fits beneath navigation at %s" % [page, dimensions])
			check(panel.get_global_rect().position.y >= MainMenu.HEADER_HEIGHT, "Page %s leaves Start accessible" % page)
			await capture(client, "main-menu-%s-%d" % [page, dimensions.x])
			await press(client, KEY_ESCAPE)
			check(client.preflight and client.paused and menu.home.visible, "Esc returns from %s without launching" % page)
	await click(client, menu.navigation["settings"])
	check(client.settings_menu.panel.visible and not client.settings_menu.pause_panel.visible, "Settings opens without a flight pause panel")
	client.settings_menu.close()
	await settle()
	check(menu.home.visible and client.paused, "Settings returns to the docked overview")
	await click(client, menu.navigation["connection"])
	check(client.session.menu.visible, "Connection management remains accessible")
	client.session.back_button.pressed.emit()
	await settle()
	check(menu.home.visible and not client.session.menu.visible and client.paused, "Connection Back returns to overview")
	await click(client, menu.navigation["shop"])
	await click(client, client.shop.buys["laser"])
	await replicate(server)
	check(client.credits == 9000 and client.session.combat.inventory["items"].has("purchase-1"), "Docked shop purchase commits to persistent inventory")
	await click(client, menu.navigation["hangar"])
	client.equipment_menu.move_item("purchase-1", "laser2")
	await settle()
	await replicate(server)
	check(ship.laser_damage == 130 and client.session.combat.inventory["items"]["purchase-1"]["slot"] == "laser2", "Docked hangar installs the purchased laser authoritatively")
	await click(client, menu.navigation["shop"])
	client.shop.select_category("ships")
	client.shop.select_model("phoenix")
	await settle()
	await click(client, client.shop.buys["phoenix"])
	await replicate(server)
	var phoenix := ShipCatalog.owned_id(client.session.combat.inventory, "phoenix")
	check(not phoenix.is_empty(), "Docked shop can buy a hull into the hangar")
	await click(client, menu.navigation["hangar"])
	client.equipment_menu.ship_choice.select(client.equipment_menu.owned_ships.find(phoenix))
	await settle()
	await click(client, client.equipment_menu.activate_button)
	await replicate(server)
	check(ship.ship_model == "phoenix" and client.player.ship_model == "phoenix" and not ship.visible and ship.collision_layer == 0, "Docked ship activation updates the hull without entering the map")
	client.equipment_menu.ship_choice.select(client.equipment_menu.owned_ships.find("starter"))
	await settle()
	await click(client, client.equipment_menu.activate_button)
	await replicate(server)
	check(ship.ship_model == "liberator" and ship.laser_damage == 130, "Switching back retains the prepared Liberator fitting")
	await click(client, menu.navigation["quests"])
	await click(client, client.hud.contract_accept)
	await replicate(server)
	check(not client.active_contracts.is_empty(), "Docked quest board accepts a saved hunt")
	await click(client, menu.start_button)
	client.session.launch_request.rpc_id(1)
	await settle()
	await replicate(server)
	check(not client.preflight and not client.paused and not menu.visible and not client.hud.contract_panel.visible, "Start closes preparation screens and enters flight")
	check(not ship.get_meta("docked") and ship.visible and ship.collision_layer == 2, "Launch enables the server ship and collision")
	var delayed := server.session.combat.pack_player(id)
	delayed.merge({"docked": true, "position": ship.position, "rotation": ship.rotation, "velocity": ship.velocity, "energy": ship.energy}, true)
	client.session.snapshot({id: delayed}, {}, client.session.player_sequences[id] + 1)
	check(client.player.visible and client.player.collision_layer == 2, "Delayed docked snapshot cannot hide a launched ship")
	check(observer.session.ships.has(id) and observer.session.ships[id].laser_damage == 130, "Other pilots see the equipped ship after launch")
	check(ship.laser_damage == 130 and client.credits == 9000 and not client.active_contracts.is_empty(), "Launch preserves fitting, wallet and accepted quest")
	check(server.session.ships.size() == 2, "Repeated launch creates no duplicate ship")
	client.session.command_flight.rpc_id(1, Vector3(0, 0, -1), Vector3.ZERO, true, false, int(client.player.get_meta("life", 0)))
	await settle()
	server.session.tick(0.1)
	check(ship.position.z < origin.z, "Launched ship can fly")
	client.session.disconnect_session("Reconnect test")
	await settle()
	client.session.join("127.0.0.1", 24739)
	await settle(0.5)
	await replicate(server)
	check(client.preflight and menu.visible and client.credits == 9000 and client.player.laser_damage == 130 and not client.active_contracts.is_empty(), "Reconnect restores progression and requires a new explicit launch")
	server.session.disconnect_session("Server shutdown test")
	await settle()
	check(not client.preflight and not menu.visible and client.session.menu.visible, "Server loss clears preparation and returns to connection menu")
	finish()
